import org.jetbrains.kotlin.gradle.dsl.JvmTarget

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    kotlin("jvm") version "2.1.20"
    id("com.gradleup.shadow") version "9.3.0"
}

group = "me.udnek"
version = "1.0-SNAPSHOT"

java {
    toolchain.languageVersion.set(JavaLanguageVersion.of(21))
}

repositories {
    mavenCentral()
    maven("https://repo.papermc.io/repository/maven-public/")
    maven("https://oss.sonatype.org/content/groups/public/")
    maven("https://repo.dmulloy2.net/repository/public/")
    maven("https://jitpack.io")
}

dependencies {
    compileOnly("io.papermc.paper:paper-api:1.21.11-R0.1-SNAPSHOT") {
        exclude(group = "org.apache.commons", module = "commons-lang3")
    }
    compileOnly("org.apache.commons:commons-lang3:3.20.0")

    compileOnly("net.dmulloy2:ProtocolLib:5.4.0")

    compileOnly(files("C:/Users/PC/IdeaProjects/CoreU/build/libs/CoreU-1.0-SNAPSHOT.jar"))
    compileOnly(files("C:/Users/PC/IdeaProjects/JeiU/build/libs/JeiU-1.0-SNAPSHOT.jar"))
    compileOnly(files("C:/Users/PC/IdeaProjects/RpgU/build/libs/RpgU-1.0-SNAPSHOT.jar"))
    compileOnly(files("C:/Users/PC/IdeaProjects/ToughAsNailsU/build/libs/ToughAsNailsU-1.0-SNAPSHOT.jar"))

    implementation("com.github.LeonMangler:SuperVanish:6.2.18-3")
}

tasks {
    compileKotlin {
        compilerOptions.jvmTarget.set(JvmTarget.JVM_21)
    }
    compileJava {
        options.release.set(21)
    }
    shadowJar {
        archiveBaseName.set("ScamShieldMain")
        archiveClassifier.set("")
        archiveVersion.set(version.toString())
    }
}