name: ScamShieldMain
version: '1.0-SNAPSHOT'
main: me.udnek.scamshieldmain.ScamShieldMain
api-version: '1.21.4'
depend: [RpgU,JeiU,ToughAsNailsU,ItemsCoreU,SuperVanish]
commands:
  infinite_regen:
    description: "infinite_regen"
    usage: "/infinite_regen"
    aliases: [ ]
    permission: tanu.admin
    permission-message: "You do not have permission to use this command"