name: ScamShieldMain
version: '1.0-SNAPSHOT'
main: me.udnek.scamshieldmain.ScamShieldMain
api-version: '1.21'
depend: [RpgU,JeiU,ToughAsNailsU,ItemsCoreU]
commands:
  infiniteregen:
    description: "infiniteregen"
    usage: "/infiniteregen"
    aliases: [ ]
    permission: tanu.admin
    permission-message: "You do not have permission to use this command"